version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download CodeClimate reporter
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt

      # Lint
      - run:
          name: Lint
          command: |
            python -m pylint --rcfile=~/repo/.pylintrc ~/repo/skylab_studio/ ~/repo/test/*

      # Unit tests
      - run:
          name: run tests
          command: |
            ./tmp/cc-test-reporter before-build
            python -m pytest --cov-report xml --cov=skylab_studio
            ./tmp/cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - staging
                - production
