version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Download system dependencies
          command: |
            sudo apt install pylint

      # Download CodeClimate reporter
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      # Lint
      - run:
          name: Lint
          command: pylint --rcfile=~/repo/.pylintrc ~/repo/skylab_genesis/ ~/repo/test/*

      # Unit tests
      - run:
          name: run tests
          command: |
            python -m pytest --cov-report xml --cov=skylab_genesis
            ./tmp/cc-test-reporter upload-coverage -i coverage.xml

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - staging
                - production